[package]
name = "droply-application"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
droply-domain = { workspace = true }
async-trait = { workspace = true }
url = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
